spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3333/personalInfo?serverTimezone=Asia/Seoul
    username: admin
    password: 5730

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 0